"""Criando tabelas iniciais

Revision ID: 558049f3ae44
Revises: 
Create Date: 2025-02-24 00:06:26.180546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '558049f3ae44'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('__EFMigrationsHistory')
    op.drop_table('Livros')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Livros',
    sa.Column('Id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('Titulo', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('Autor', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('AnoPublicacao', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Id', name='PK_Livros')
    )
    op.create_table('__EFMigrationsHistory',
    sa.Column('MigrationId', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('ProductVersion', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('MigrationId', name='PK___EFMigrationsHistory')
    )
    # ### end Alembic commands ###
